"""Initial migration

Revision ID: dca99e392f6d
Revises: 
Create Date: 2023-10-02 12:48:19.843238

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dca99e392f6d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
